version: "3"

# This file is for local development with mocked hardware libraries. This is
# used for local development on hw_display/ code (See README)

services:
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"

  api:
    build: ./api/
    command: cargo watch -x run
    init: true # Fixes slow shutdown
    tty: true # Colorize output
    depends_on:
      - redis
    volumes:
      - ./api/:/app/api
      - api_build:/app/api/target
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
      - ROCKET_REDIS_URL=redis://redis:6379/0
      - ROCKET_ADDRESS=0.0.0.0
    ports:
      - "8000:8000"

  reducer:
    build: ./reducer/
    depends_on:
      - redis
    volumes:
      - ./reducer:/app/reducer

  display:
    build: ./hw_display
    command: sh -c "mkdir -p mock_logs && python -m soze_display -r redis://redis:6379/0"
    depends_on:
      - redis
    volumes:
      - ./hw_display:/app/display
