version: "3"

services:
  redis:
    image: redis:5
    ports:
      - "6379:6379"

  reducer:
    build: ./reducer/
    command: python -m soze_reducer
    depends_on:
      - redis
    volumes:
      - ./reducer:/app/soze/reducer
    environment:
      - REDIS_HOST=redis://redis:6379/0

  api:
    build: ./api/
    command: flask run --host=0.0.0.0
    depends_on:
      - redis
    volumes:
      - ./api:/app/soze/api
    environment:
      - FLASK_APP=soze_api.api
      - FLASK_ENV=development
      - REDIS_HOST=redis://redis:6379/0
    ports:
      - "5000:5000"
  # webapp:
  #   build: ./webapp/
  #   command: sh -c "npm i && npm start"
  #   volumes:
  #     - ./webapp/:/app/soze/webapp:rw
  #   environment:
  #     - NODE_ENV=development
  #     - SOZE_API_HOST=http://api:5000/
  #   ports:
  #     - "3000"
