version: "3"

# This defines the stack that runs on the Pi. All images used here have to be
# pre-built, and are pulled from the cloud.

services:
  redis:
    # For some reason redis:5-alpine doesn't work (segfaults) even though it
    # has an arm32v6 version in its manifest ¯\_(ツ)_/¯
    image: arm32v6/redis:5-alpine
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/data

  api:
    image: ghcr.io/lucaspickering/soze-api
    restart: on-failure
    depends_on:
      - redis
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=info
      - ROCKET_REDIS_URL=redis://redis:6379/0
      - ROCKET_ADDRESS=0.0.0.0

  reducer:
    image: ghcr.io/lucaspickering/soze-reducer
    restart: on-failure
    depends_on:
      - redis
      - display # Force reducer to stop first
    volumes:
      # Sync the system timezone into the container
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  display:
    image: ghcr.io/lucaspickering/soze-display
    restart: on-failure
    depends_on:
      - redis
    privileged: true # Needed for hardware interaction

  webserver:
    image: ghcr.io/lucaspickering/soze-webserver
    restart: on-failure
    depends_on:
      - api
    ports:
      - "80:80"
