version: "3"

# Use these instead of the local directory for building the projects
# to prevent the containers from fighting with external build tools
volumes:
  node_modules:

services:
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"

  api:
    build: ./api/
    command: flask run --host=0.0.0.0
    depends_on:
      - redis
    volumes:
      - ./api:/app/api
    environment:
      - FLASK_APP=soze_api.api
      - FLASK_ENV=development
      - REDIS_HOST=redis://redis:6379/0
    ports:
      - "5000:5000"

  reducer:
    build: ./reducer/
    command: python -m soze_reducer -r redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./reducer:/app/reducer

  webapp:
    image: node:10-alpine
    working_dir: /app/webapp
    command: sh -c "npm i && npm start"
    volumes:
      - ./soze:/app/webapp:rw
      - node_modules:/app/webapp/node_modules
    environment:
      - NODE_ENV=development
      - SOZE_API_HOST=http://api:5000/
    ports:
      - "3000:3000"
