version: "3"

# This file is for local development with mocked hardware libraries. This is
# used for local development on hw_display/ code (See README)

services:
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"

  api:
    build: ./api/
    depends_on:
      - redis
    volumes:
      - ./api:/app/api
    environment:
      - FLASK_APP=soze_api.api
      - FLASK_ENV=development
      - REDIS_HOST=redis://redis:6379/0
    ports:
      - "5000:5000"

  reducer:
    build: ./reducer/
    depends_on:
      - redis
    volumes:
      - ./reducer:/app/reducer

  display:
    build: ./hw_display
    command: sh -c "mkdir -p mock_logs && python -m soze_display -r redis://redis:6379/0"
    depends_on:
      - redis
    volumes:
      - ./hw_display:/app/display
