version: "3"

services:
  redis:
    image: arm32v6/redis:5-alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/data

  api:
    build:
      context: ./api/
      dockerfile: pi.Dockerfile
    restart: always
    depends_on:
      - redis
    environment:
      - FLASK_APP=soze_api.api
      - FLASK_ENV=development
      - REDIS_HOST=redis://redis:6379/0

  reducer:
    build:
      context: ./reducer/
      dockerfile: pi.Dockerfile
    restart: always
    depends_on:
      - redis
      - display # Force reducer to stop first
    volumes:
      # Sync the system timezone into the container
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro

  display:
    build:
      context: ./hw_display/
      dockerfile: pi.Dockerfile
    restart: always
    depends_on:
      - redis
    privileged: true

  webserver:
    build:
      context: ./webapp/
      dockerfile: pi.Dockerfile
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"
