version: "3"

services:
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"
    volumes:
      - /data/redis:/data

  api:
    build: ./api/
    command: flask run --host=0.0.0.0
    depends_on:
      - redis
    environment:
      - FLASK_APP=soze_api.api
      - FLASK_ENV=development
      - REDIS_HOST=redis://redis:6379/0
    ports:
      - "5000:5000"

  reducer:
    build: ./reducer/
    command: python -m soze_reducer -r redis://redis:6379/0
    depends_on:
      - redis

  display:
    build: ./hw_display/
    command: python -m soze_display -r redis://redis:6379/0
    depends_on:
      - redis
    privileged: true
