version: "3"

# This file defines the stack for most development. This should be used with
# the mock_display/ script (See README)

# Use these instead of the local directory for building the projects
# to prevent the containers from fighting with external build tools
volumes:
  api_build:
  node_modules:

services:
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"

  api:
    build: ./api/
    command: cargo watch -x run
    init: true # Fixes slow shutdown
    tty: true # Colorize output
    depends_on:
      - redis
    volumes:
      - ./api/:/app/api
      - api_build:/app/api/target
    environment:
      - RUST_BACKTRACE=1
      - RUST_LOG=debug
      - ROCKET_REDIS_URL=redis://redis:6379/0
      - ROCKET_ADDRESS=0.0.0.0
    ports:
      - "8000:8000"

  reducer:
    build: ./reducer/
    command: python -m soze_reducer -r redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./reducer:/app/reducer

  webapp:
    image: node:lts-alpine
    working_dir: /app/webapp
    command: sh -c "npm i && npm start"
    volumes:
      - ./webapp:/app/webapp:rw
      - node_modules:/app/webapp/node_modules
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - BROWSER=none
      - SOZE_API_HOST=http://api:8000/
    ports:
      - "3000:3000"
