version: "3"

services:
  redis:
    image: redis:5-alpine
    ports:
      - "6379:6379"

  api:
    build: ./api/
    command: flask run --host=0.0.0.0
    depends_on:
      - redis
    volumes:
      - ./api:/app/soze/api
    environment:
      - FLASK_APP=soze_api.api
      - FLASK_ENV=development
      - REDIS_HOST=redis://redis:6379/0
    ports:
      - "5000:5000"

  reducer:
    build: ./reducer/
    command: python -m soze_reducer -r redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./reducer:/app/soze/reducer

  display:
    build:
      context: ./hw_display
      dockerfile: mock.Dockerfile
    command: python -m soze_display -r redis://redis:6379/0
    depends_on:
      - redis
    volumes:
      - ./hw_display:/app/soze/display
